# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 126175fcd2e2fcd5447907f360bc9e0bb5741ca8242cb6ef4536f0916e4a4daacf81514eb6b0e4dc44d320c7474e82f0f15a529cceec2eccddb49d5a42f36ac1

test:
  secret_key_base: 784db4de03643c05440774aac73fc0384a1ad1d8f8acca5d8ea62b3804f63dcf5f9d9fb67e7cc7b6c33738c94b5263814ca699ea7ad6fc721a96eeddee6829e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
